version: "3.9"

services:
  db:
    image: postgres:14
    container_name: challenge_db_test
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: challenge_tests_runner
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/challenge"
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["poetry", "run", "pytest", "-vv", "--disable-warnings"]
    restart: "no"

volumes:
  pgdata:
